"""updated the pitches class

Revision ID: f81b468cb2a6
Revises: a10342d4d9de
Create Date: 2017-11-07 08:16:53.676907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f81b468cb2a6'
down_revision = 'a10342d4d9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('comment_section_id', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'pitches', ['pitches_id'], ['id'])
    op.add_column('pitches', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'category_title')
    op.drop_column('pitches', 'category_date')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    op.add_column('pitches', sa.Column('category_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'date_posted')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'pitches_id')
    op.drop_column('comments', 'comment_section_id')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
